// Generated from data/destination-media-audit.json.
// Keys include province names to avoid collisions between similarly named places.
export const destinationImages: Record<string, string> = {
  "Anhui::Chengkan Village": "/images/destinations/optimized/wiki-anhui-chengkan-village.jpg",
  "Anhui::Hongcun": "/images/destinations/optimized/wiki-anhui-hongcun.jpg",
  "Anhui::Huangshan": "/images/destinations/optimized/wiki-anhui-huangshan.jpg",
  "Anhui::Jiuhua Mountain": "/images/destinations/optimized/wiki-anhui-jiuhua-mountain.jpg",
  "Anhui::Shexian Ancient City": "/images/destinations/optimized/wiki-anhui-shexian-ancient-city.jpg",
  "Anhui::Taiping Lake": "/images/destinations/optimized/wiki-anhui-taiping-lake.jpg",
  "Anhui::Tunxi Old Street": "/images/destinations/optimized/wiki-anhui-tunxi-old-street.jpg",
  "Anhui::Xidi": "/images/destinations/optimized/wiki-anhui-xidi.jpg",
  "Anhui::Xuancheng Xuan Paper Workshop": "/images/destinations/optimized/wiki-anhui-xuancheng-xuan-paper-workshop.jpg",
  "Beijing::798 Art District": "/images/destinations/optimized/wiki-beijing-798-art-district.jpg",
  "Beijing::Beijing Breakfast Walk": "/images/destinations/optimized/wiki-beijing-beijing-breakfast-walk.jpg",
  "Beijing::Forbidden City": "/images/destinations/optimized/wiki-beijing-forbidden-city.jpg",
  "Beijing::Hutong Family Visit": "/images/experience-beijing-hutong.jpg",
  "Beijing::Lama Temple": "/images/destinations/optimized/wiki-beijing-lama-temple.jpg",
  "Beijing::Mutianyu Great Wall": "/images/destinations/optimized/wiki-beijing-mutianyu-great-wall.jpg",
  "Beijing::Panjiayuan Market": "/images/destinations/optimized/wiki-beijing-panjiayuan-market.jpg",
  "Beijing::Summer Palace": "/images/destinations/optimized/wiki-beijing-summer-palace.jpg",
  "Beijing::Temple of Heaven": "/images/destinations/optimized/wiki-beijing-temple-of-heaven.jpg",
  "Chongqing::Chongqing Hotpot Kitchen": "/images/destinations/optimized/wiki-chongqing-chongqing-hotpot-kitchen.jpg",
  "Chongqing::Ciqikou Old Town": "/images/destinations/optimized/wiki-chongqing-ciqikou-old-town.jpg",
  "Chongqing::Dazu Rock Carvings": "/images/destinations/optimized/wiki-chongqing-dazu-rock-carvings.jpg",
  "Chongqing::Fengdu Ghost City": "/images/destinations/optimized/wiki-chongqing-fengdu-ghost-city.jpg",
  "Chongqing::Hongya Cave": "/images/destinations/optimized/wiki-chongqing-hongya-cave.jpg",
  "Chongqing::Jiefangbei Night Walk": "/images/destinations/optimized/wiki-chongqing-jiefangbei-night-walk.jpg",
  "Chongqing::Liziba Light Rail": "/images/destinations/optimized/wiki-chongqing-liziba-light-rail.jpg",
  "Chongqing::Wulong Karst": "/images/destinations/optimized/wiki-chongqing-wulong-karst.jpg",
  "Chongqing::Yangtze Cableway": "/images/destinations/optimized/wiki-chongqing-yangtze-cableway.jpg",
  "Fujian::Anxi Tea Villages": "/images/destinations/optimized/wiki-fujian-anxi-tea-villages.jpg",
  "Fujian::Fujian Tulou": "/images/destinations/optimized/wiki-fujian-fujian-tulou.jpg",
  "Fujian::Fuzhou Three Lanes Seven Alleys": "/images/destinations/optimized/wiki-fujian-fuzhou-three-lanes-seven-alleys.jpg",
  "Fujian::Meizhou Mazu Temple": "/images/destinations/optimized/wiki-fujian-meizhou-mazu-temple.jpg",
  "Fujian::Quanzhou Maritime Heritage": "/images/destinations/optimized/wiki-fujian-quanzhou-maritime-heritage.jpg",
  "Fujian::Quanzhou Puppet Workshop": "/images/experience-quanzhou-puppet.jpg",
  "Fujian::Wuyi Mountains": "/images/destinations/optimized/wiki-fujian-wuyi-mountains.jpg",
  "Fujian::Xiamen Gulangyu": "/images/destinations/optimized/wiki-fujian-xiamen-gulangyu.jpg",
  "Fujian::Xiapu Mudflats": "/images/destinations/optimized/wiki-fujian-xiapu-mudflats.jpg",
  "Gansu::Bingling Temple Grottoes": "/images/destinations/optimized/wiki-gansu-bingling-temple-grottoes.jpg",
  "Gansu::Dunhuang Night Market": "/images/destinations/optimized/wiki-gansu-dunhuang-night-market.jpg",
  "Gansu::Hexi Corridor Road": "/images/destinations/optimized/wiki-gansu-hexi-corridor-road.jpg",
  "Gansu::Jiayuguan Pass": "/images/destinations/optimized/wiki-gansu-jiayuguan-pass.jpg",
  "Gansu::Labrang Monastery": "/images/destinations/optimized/wiki-gansu-labrang-monastery.jpg",
  "Gansu::Maijishan Grottoes": "/images/destinations/optimized/wiki-gansu-maijishan-grottoes.jpg",
  "Gansu::Mingsha Mountain and Crescent Spring": "/images/destinations/optimized/wiki-gansu-mingsha-mountain-and-crescent-spring.jpg",
  "Gansu::Mogao Caves": "/images/destinations/optimized/wiki-gansu-mogao-caves.jpg",
  "Gansu::Zhangye Danxia": "/images/destinations/optimized/wiki-gansu-zhangye-danxia.jpg",
  "Guangdong::Chaozhou Old Town": "/images/destinations/optimized/wiki-guangdong-chaozhou-old-town.jpg",
  "Guangdong::Chen Clan Ancestral Hall": "/images/destinations/optimized/wiki-guangdong-chen-clan-ancestral-hall.jpg",
  "Guangdong::Foshan Ancestral Temple": "/images/destinations/optimized/wiki-guangdong-foshan-ancestral-temple.jpg",
  "Guangdong::Guangzhou Old City": "/images/destinations/optimized/wiki-guangdong-guangzhou-old-city.jpg",
  "Guangdong::Kaiping Diaolou": "/images/destinations/optimized/wiki-guangdong-kaiping-diaolou.jpg",
  "Guangdong::Liwan Food Market": "/images/destinations/optimized/wiki-guangdong-liwan-food-market.jpg",
  "Guangdong::Shenzhen Urban Villages": "/images/destinations/optimized/wiki-guangdong-shenzhen-urban-villages.jpg",
  "Guangdong::Shiwan Ceramic Studio": "/images/experience-shiwan-ceramics.jpg",
  "Guangdong::Xiqiao Mountain": "/images/destinations/optimized/wiki-guangdong-xiqiao-mountain.jpg",
  "Guangxi::Bama Longevity Villages": "/images/destinations/optimized/wiki-guangxi-longji-rice-terraces.jpg",
  "Guangxi::Beihai Old Street": "/images/destinations/optimized/wiki-guangxi-beihai-old-street.jpg",
  "Guangxi::Chengyang Wind and Rain Bridge": "/images/destinations/optimized/wiki-guangxi-chengyang-wind-and-rain-bridge.jpg",
  "Guangxi::Detian Waterfall": "/images/destinations/optimized/wiki-guangxi-detian-waterfall.jpg",
  "Guangxi::Guilin Rice Noodle Trail": "/images/experience-yangshuo-farm-food.jpg",
  "Guangxi::Li River": "/images/destinations/optimized/wiki-guangxi-li-river.jpg",
  "Guangxi::Longji Rice Terraces": "/images/destinations/optimized/wiki-guangxi-longji-rice-terraces.jpg",
  "Guangxi::Nanning Morning Market": "/images/experience-liwan-fresh-market-stalls-real.jpg?v=2",
  "Guangxi::Yangshuo Countryside": "/images/destinations/optimized/wiki-guangxi-yangshuo-countryside.jpg",
  "Guizhou::Fanjing Mountain": "/images/destinations/optimized/wiki-guizhou-fanjing-mountain.jpg",
  "Guizhou::Huangguoshu Waterfall": "/images/destinations/optimized/wiki-guizhou-huangguoshu-waterfall.jpg",
  "Guizhou::Kaili Market": "/images/destinations/optimized/wiki-guizhou-kaili-market.jpg",
  "Guizhou::Libo Xiaoqikong": "/images/destinations/optimized/wiki-guizhou-libo-xiaoqikong.jpg",
  "Guizhou::Maotai Town": "/images/destinations/optimized/wiki-guizhou-maotai-town.jpg",
  "Guizhou::Miao Embroidery Workshop": "/images/experience-miao-craft.jpg",
  "Guizhou::Qingyan Ancient Town": "/images/destinations/optimized/wiki-guizhou-qingyan-ancient-town.jpg",
  "Guizhou::Xijiang Miao Village": "/images/destinations/optimized/wiki-guizhou-xijiang-miao-village.jpg",
  "Guizhou::Zhaoxing Dong Village": "/images/destinations/optimized/wiki-guizhou-zhaoxing-dong-village.jpg",
  "Hainan::Binglanggu Li and Miao Culture": "/images/destinations/optimized/wiki-hainan-binglanggu-li-and-miao-culture.jpg",
  "Hainan::Boao Town": "/images/about-me-boat-seafood.jpg",
  "Hainan::Dongpo Academy Danzhou": "/images/destinations/optimized/wiki-hainan-dongpo-academy-danzhou.jpg",
  "Hainan::Haikou Qilou Old Street": "/images/destinations/optimized/wiki-hainan-haikou-qilou-old-street.jpg",
  "Hainan::Hainan Family Kitchen": "/images/destinations/optimized/wiki-hainan-hainan-family-kitchen.jpg",
  "Hainan::Sanya Coast": "/images/destinations/optimized/wiki-hainan-sanya-coast.jpg",
  "Hainan::Tanmen Fishing Port": "/images/about-me-boat-seafood.jpg",
  "Hainan::Wuzhishan Rainforest": "/images/destinations/optimized/wiki-hainan-wuzhishan-rainforest.jpg",
  "Hainan::Yalong Bay Tropical Forest": "/images/destinations/optimized/wiki-hainan-yalong-bay-tropical-forest.jpg",
  "Hebei::Baiyangdian Wetland": "/images/destinations/optimized/wiki-hebei-baiyangdian-wetland.jpg",
  "Hebei::Beidaihe Coast": "/images/destinations/optimized/wiki-hebei-beidaihe-coast.jpg",
  "Hebei::Cangzhou Martial Arts": "/images/destinations/optimized/wiki-hebei-cangzhou-martial-arts.jpg",
  "Hebei::Chengde Mountain Resort": "/images/destinations/optimized/wiki-hebei-chengde-mountain-resort.jpg",
  "Hebei::Mulan Weichang": "/images/destinations/optimized/wiki-hebei-mulan-weichang.jpg",
  "Hebei::Shanhaiguan Pass": "/images/destinations/optimized/wiki-hebei-shanhaiguan-pass.jpg",
  "Hebei::Xibaipo": "/images/destinations/optimized/wiki-hebei-xibaipo.jpg",
  "Hebei::Zhaozhou Bridge": "/images/destinations/optimized/wiki-hebei-zhaozhou-bridge.jpg",
  "Hebei::Zhengding Ancient City": "/images/destinations/optimized/wiki-hebei-zhengding-ancient-city.jpg",
  "Heilongjiang::Beiji Village Mohe": "/images/destinations/optimized/wiki-heilongjiang-beiji-village-mohe.jpg",
  "Heilongjiang::Central Street Harbin": "/images/destinations/optimized/wiki-heilongjiang-central-street-harbin.jpg",
  "Heilongjiang::Daqing Petroleum Memory": "/images/destinations/optimized/wiki-heilongjiang-daqing-petroleum-memory.jpg",
  "Heilongjiang::Harbin Ice and Snow World": "/images/destinations/optimized/wiki-heilongjiang-harbin-ice-and-snow-world.jpg",
  "Heilongjiang::Saint Sophia Cathedral": "/images/destinations/optimized/wiki-heilongjiang-saint-sophia-cathedral.jpg",
  "Heilongjiang::Volga Manor": "/images/destinations/optimized/wiki-heilongjiang-volga-manor.jpg",
  "Heilongjiang::Wudalianchi": "/images/destinations/optimized/wiki-heilongjiang-wudalianchi.jpg",
  "Heilongjiang::Yabuli Ski Area": "/images/destinations/optimized/wiki-heilongjiang-yabuli-ski-area.jpg",
  "Heilongjiang::Zhalong Wetland": "/images/destinations/optimized/wiki-heilongjiang-zhalong-wetland.jpg",
  "Henan::Chenjiagou Taiji Village": "/images/destinations/optimized/wiki-henan-chenjiagou-taiji-village.jpg",
  "Henan::Guoliang Village": "/images/destinations/optimized/wiki-henan-guoliang-village.jpg",
  "Henan::Kaifeng Old City": "/images/destinations/optimized/wiki-henan-kaifeng-old-city.jpg",
  "Henan::Longmen Grottoes": "/images/destinations/optimized/wiki-henan-longmen-grottoes.jpg",
  "Henan::Luoyang Peony Season": "/images/destinations/optimized/wiki-henan-luoyang-peony-season.jpg",
  "Henan::Shaolin Temple": "/images/destinations/optimized/wiki-henan-shaolin-temple.jpg",
  "Henan::Yellow River Scenic Area Zhengzhou": "/images/destinations/optimized/wiki-henan-yellow-river-scenic-area-zhengzhou.jpg",
  "Henan::Yinxu Anyang": "/images/destinations/optimized/wiki-henan-yinxu-anyang.jpg",
  "Henan::Zhengzhou Museum and Market": "/images/destinations/optimized/wiki-henan-zhengzhou-museum-and-market.jpg",
  "Hong Kong::Central Mid-Levels Walk": "/images/destinations/optimized/wiki-hong-kong-central-mid-levels-walk.jpg",
  "Hong Kong::Dragon Back Trail": "/images/destinations/optimized/wiki-hong-kong-dragon-back-trail.jpg",
  "Hong Kong::Lantau Island": "/images/destinations/optimized/wiki-hong-kong-lantau-island.jpg",
  "Hong Kong::Man Mo Temple": "/images/destinations/optimized/wiki-hong-kong-man-mo-temple.jpg",
  "Hong Kong::Mong Kok Markets": "/images/destinations/optimized/wiki-hong-kong-mong-kok-markets.jpg",
  "Hong Kong::Star Ferry": "/images/destinations/optimized/wiki-hong-kong-star-ferry.jpg",
  "Hong Kong::Tai O Fishing Village": "/images/destinations/optimized/wiki-hong-kong-tai-o-fishing-village.jpg",
  "Hong Kong::Temple Street Night Market": "/images/destinations/optimized/wiki-hong-kong-temple-street-night-market.jpg",
  "Hong Kong::Victoria Peak": "/images/destinations/optimized/wiki-hong-kong-victoria-peak.jpg",
  "Hubei::East Lake Wuhan": "/images/destinations/optimized/wiki-hubei-east-lake-wuhan.jpg",
  "Hubei::Enshi Grand Canyon": "/images/destinations/optimized/wiki-hubei-enshi-grand-canyon.jpg",
  "Hubei::Hubei Provincial Museum": "/images/destinations/optimized/wiki-hubei-hubei-provincial-museum.jpg",
  "Hubei::Jingzhou Ancient City": "/images/destinations/optimized/wiki-hubei-jingzhou-ancient-city.jpg",
  "Hubei::Shennongjia Forest": "/images/destinations/optimized/wiki-hubei-shennongjia-forest.jpg",
  "Hubei::Three Gorges Hubei Section": "/images/destinations/optimized/wiki-hubei-three-gorges-hubei-section.jpg",
  "Hubei::Wudang Mountains": "/images/destinations/optimized/wiki-hubei-wudang-mountains.jpg",
  "Hubei::Wuhan Breakfast Streets": "/images/destinations/optimized/wiki-hubei-wuhan-breakfast-streets.jpg",
  "Hubei::Yellow Crane Tower": "/images/destinations/optimized/wiki-hubei-yellow-crane-tower.jpg",
  "Hunan::Changsha Night Food": "/images/destinations/optimized/wiki-hunan-changsha-night-food.jpg",
  "Hunan::Dehang Miao Village": "/images/destinations/optimized/wiki-hunan-dehang-miao-village.jpg",
  "Hunan::Dongjiang Lake": "/images/destinations/optimized/wiki-hunan-dongjiang-lake.jpg",
  "Hunan::Fenghuang Ancient Town": "/images/destinations/optimized/wiki-hunan-fenghuang-ancient-town.jpg",
  "Hunan::Orange Isle": "/images/destinations/optimized/wiki-hunan-orange-isle.jpg",
  "Hunan::Shaoshan": "/images/destinations/optimized/wiki-hunan-shaoshan.jpg",
  "Hunan::Yuelu Academy": "/images/destinations/optimized/wiki-hunan-yuelu-academy.jpg",
  "Hunan::Yueyang Tower": "/images/destinations/optimized/wiki-hunan-yueyang-tower.jpg",
  "Hunan::Zhangjiajie National Forest Park": "/images/destinations/optimized/wiki-hunan-zhangjiajie-national-forest-park.jpg",
  "Inner Mongolia::Arxan National Forest": "/images/destinations/optimized/wiki-inner-mongolia-arxan-national-forest.jpg",
  "Inner Mongolia::Erguna Wetland": "/images/destinations/optimized/wiki-inner-mongolia-erguna-wetland.jpg",
  "Inner Mongolia::Genghis Khan Mausoleum": "/images/destinations/optimized/wiki-inner-mongolia-genghis-khan-mausoleum.jpg",
  "Inner Mongolia::Hohhot Old City": "/images/destinations/optimized/wiki-inner-mongolia-hohhot-old-city.jpg",
  "Inner Mongolia::Hulunbuir Grassland": "/images/destinations/optimized/wiki-inner-mongolia-hulunbuir-grassland.jpg",
  "Inner Mongolia::Kubuqi Desert": "/images/destinations/optimized/wiki-inner-mongolia-kubuqi-desert.jpg",
  "Inner Mongolia::Manzhouli": "/images/destinations/optimized/wiki-inner-mongolia-manzhouli.jpg",
  "Inner Mongolia::Wudangzhao Monastery": "/images/destinations/optimized/wiki-inner-mongolia-wudangzhao-monastery.jpg",
  "Inner Mongolia::Xilamuren Grassland": "/images/destinations/optimized/wiki-inner-mongolia-xilamuren-grassland.jpg",
  "Jiangsu::Grand Canal Suzhou Section": "/images/destinations/optimized/wiki-jiangsu-grand-canal-suzhou-section.jpg",
  "Jiangsu::Huaiyang Cuisine Kitchen": "/images/destinations/optimized/wiki-jiangsu-huaiyang-cuisine-kitchen.jpg",
  "Jiangsu::Nanjing City Wall": "/images/destinations/optimized/wiki-jiangsu-nanjing-city-wall.jpg",
  "Jiangsu::Nanjing Confucius Temple Area": "/images/destinations/optimized/wiki-jiangsu-nanjing-confucius-temple-area.jpg",
  "Jiangsu::Suzhou Classical Gardens": "/images/destinations/optimized/wiki-jiangsu-suzhou-classical-gardens.jpg",
  "Jiangsu::Suzhou Silk Embroidery": "/images/destinations/optimized/wiki-jiangsu-suzhou-silk-embroidery.jpg",
  "Jiangsu::Yangzhou Slender West Lake": "/images/destinations/optimized/wiki-jiangsu-yangzhou-slender-west-lake.jpg",
  "Jiangsu::Yixing Zisha Teapot Studio": "/images/destinations/optimized/wiki-jiangsu-yixing-zisha-teapot-studio.jpg",
  "Jiangsu::Zhouzhuang Water Town": "/images/destinations/optimized/wiki-jiangsu-zhouzhuang-water-town.jpg",
  "Jiangxi::Ganzhou Old City Wall": "/images/destinations/optimized/wiki-jiangxi-ganzhou-old-city-wall.jpg",
  "Jiangxi::Jingdezhen Porcelain Workshops": "/images/destinations/optimized/wiki-jiangxi-jingdezhen-porcelain-workshops.jpg",
  "Jiangxi::Jinggangshan": "/images/destinations/optimized/wiki-jiangxi-jinggangshan.jpg",
  "Jiangxi::Lushan Cloud Tea": "/images/experience-mengding-tea.jpg",
  "Jiangxi::Mount Lushan": "/images/destinations/optimized/wiki-jiangxi-mount-lushan.jpg",
  "Jiangxi::Poyang Lake": "/images/destinations/optimized/wiki-jiangxi-poyang-lake.jpg",
  "Jiangxi::Sanqing Mountain": "/images/destinations/optimized/wiki-jiangxi-sanqing-mountain.jpg",
  "Jiangxi::Tengwang Pavilion": "/images/destinations/optimized/wiki-jiangxi-tengwang-pavilion.jpg",
  "Jiangxi::Wuyuan Villages": "/images/destinations/optimized/wiki-jiangxi-wuyuan-villages.jpg",
  "Jilin::Chagan Lake Winter Fishing": "/images/destinations/optimized/wiki-jilin-chagan-lake-winter-fishing.jpg",
  "Jilin::Changbai Mountain": "/images/destinations/optimized/wiki-jilin-changbai-mountain.jpg",
  "Jilin::Changchun Puppet Palace": "/images/destinations/optimized/wiki-jilin-changchun-puppet-palace.jpg",
  "Jilin::Hunchun Border View": "/images/destinations/optimized/wiki-jilin-hunchun-border-view.jpg",
  "Jilin::Jilin Rime Island": "/images/destinations/optimized/wiki-jilin-jilin-rime-island.jpg",
  "Jilin::Jingyuetan Forest": "/images/destinations/optimized/wiki-jilin-jingyuetan-forest.jpg",
  "Jilin::Koguryo Heritage Ji'an": "/images/destinations/optimized/wiki-jilin-koguryo-heritage-ji-an.jpg",
  "Jilin::Songhua Lake": "/images/destinations/optimized/wiki-jilin-songhua-lake.jpg",
  "Jilin::Yanji Food Streets": "/images/destinations/optimized/wiki-jilin-yanji-food-streets.jpg",
  "Liaoning::Benxi Water Cave": "/images/destinations/optimized/wiki-liaoning-benxi-water-cave.jpg",
  "Liaoning::Dalian Binhai Road": "/images/destinations/optimized/wiki-liaoning-dalian-binhai-road.jpg",
  "Liaoning::Dandong Yalu River": "/images/destinations/optimized/wiki-liaoning-dandong-yalu-river.jpg",
  "Liaoning::Jinzhou Guta Night Food": "/images/destinations/optimized/wiki-liaoning-jinzhou-guta-night-food.jpg",
  "Liaoning::Liaoyang White Pagoda": "/images/destinations/optimized/wiki-liaoning-liaoyang-white-pagoda.jpg",
  "Liaoning::Panjin Red Beach": "/images/destinations/optimized/wiki-liaoning-panjin-red-beach.jpg",
  "Liaoning::Shenyang Imperial Palace": "/images/destinations/optimized/wiki-liaoning-shenyang-imperial-palace.jpg",
  "Liaoning::Xingcheng Ancient City": "/images/destinations/optimized/wiki-liaoning-xingcheng-ancient-city.jpg",
  "Liaoning::Zhang Family Mansion": "/images/destinations/optimized/wiki-liaoning-zhang-family-mansion.jpg",
  "Macau::A-Ma Temple": "/images/destinations/optimized/wiki-macau-a-ma-temple.jpg",
  "Macau::Coloane Village": "/images/destinations/optimized/wiki-macau-coloane-village.jpg",
  "Macau::Guia Fortress": "/images/destinations/optimized/wiki-macau-guia-fortress.jpg",
  "Macau::Historic Centre of Macau": "/images/destinations/optimized/wiki-macau-historic-centre-of-macau.jpg",
  "Macau::Macanese Bakery Trail": "/images/destinations/optimized/wiki-macau-macanese-bakery-trail.jpg",
  "Macau::Red Market Macau": "/images/destinations/optimized/wiki-macau-red-market-macau.jpg",
  "Macau::Ruins of St Pauls": "/images/destinations/optimized/wiki-macau-ruins-of-st-pauls.jpg",
  "Macau::Senado Square": "/images/destinations/optimized/wiki-macau-senado-square.jpg",
  "Macau::Taipa Village": "/images/destinations/optimized/wiki-macau-taipa-village.jpg",
  "Ningxia::Helan Mountain Rock Art": "/images/destinations/optimized/wiki-ningxia-helan-mountain-rock-art.jpg",
  "Ningxia::Ningxia Winery Route": "/images/destinations/optimized/wiki-ningxia-helan-mountain-rock-art.jpg",
  "Ningxia::Qingtongxia 108 Stupas": "/images/destinations/optimized/wiki-ningxia-qingtongxia-108-stupas.jpg",
  "Ningxia::Shapotou": "/images/destinations/optimized/wiki-ningxia-shapotou.jpg",
  "Ningxia::Shuidonggou": "/images/destinations/optimized/wiki-ningxia-shuidonggou.jpg",
  "Ningxia::Western Xia Tombs": "/images/destinations/optimized/wiki-ningxia-western-xia-tombs.jpg",
  "Ningxia::Wuzhong Morning Tea": "/images/experience-xian-noodles.jpg",
  "Ningxia::Yellow River Grand Canyon": "/images/destinations/optimized/wiki-ningxia-yellow-river-grand-canyon.jpg",
  "Ningxia::Zhenbeibao Western Studios": "/images/destinations/optimized/wiki-ningxia-western-xia-tombs.jpg",
  "Qinghai::Chaka Salt Lake": "/images/destinations/optimized/wiki-qinghai-chaka-salt-lake.jpg",
  "Qinghai::Dongguan Mosque": "/images/destinations/optimized/wiki-qinghai-dongguan-mosque.jpg",
  "Qinghai::Guide Yellow River": "/images/destinations/optimized/wiki-qinghai-guide-yellow-river.jpg",
  "Qinghai::Hoh Xil View Route": "/images/destinations/optimized/wiki-qinghai-hoh-xil-view-route.jpg",
  "Qinghai::Kumbum Monastery": "/images/destinations/optimized/wiki-qinghai-kumbum-monastery.jpg",
  "Qinghai::Menyuan Rapeseed Fields": "/images/destinations/optimized/wiki-jiangxi-wuyuan-villages.jpg",
  "Qinghai::Qilian Grassland": "/images/destinations/optimized/wiki-qinghai-qilian-grassland.jpg",
  "Qinghai::Qinghai Lake": "/images/destinations/optimized/wiki-qinghai-qinghai-lake.jpg",
  "Qinghai::Tongren Thangka Studios": "/images/destinations/optimized/wiki-qinghai-tongren-thangka-studios.jpg",
  "Shaanxi::Big Wild Goose Pagoda": "/images/destinations/optimized/wiki-shaanxi-big-wild-goose-pagoda.jpg",
  "Shaanxi::Famen Temple": "/images/destinations/optimized/wiki-shaanxi-famen-temple.jpg",
  "Shaanxi::Hanzhong Rapeseed Fields": "/images/destinations/optimized/wiki-jiangxi-wuyuan-villages.jpg",
  "Shaanxi::Huaqing Palace": "/images/destinations/optimized/wiki-shaanxi-huaqing-palace.jpg",
  "Shaanxi::Mount Hua": "/images/destinations/optimized/wiki-shaanxi-mount-hua.jpg",
  "Shaanxi::Muslim Quarter Xi'an": "/images/destinations/optimized/wiki-shaanxi-muslim-quarter-xi-an.jpg",
  "Shaanxi::Terracotta Army": "/images/destinations/optimized/wiki-shaanxi-terracotta-army.jpg",
  "Shaanxi::Xi'an City Wall": "/images/destinations/optimized/wiki-shaanxi-xi-an-city-wall.jpg",
  "Shaanxi::Yan'an Cave Dwellings": "/images/destinations/optimized/wiki-shaanxi-yan-an-cave-dwellings.jpg",
  "Shandong::Jinan Springs": "/images/destinations/optimized/wiki-shandong-jinan-springs.jpg",
  "Shandong::Laoshan": "/images/destinations/optimized/wiki-shandong-laoshan.jpg",
  "Shandong::Mount Tai": "/images/destinations/optimized/wiki-shandong-mount-tai.jpg",
  "Shandong::Qingdao Old Town": "/images/destinations/optimized/wiki-shandong-qingdao-old-town.jpg",
  "Shandong::Qufu Confucius Sites": "/images/destinations/optimized/wiki-shandong-qufu-confucius-sites.jpg",
  "Shandong::Rongcheng Swan Lake": "/images/destinations/optimized/wiki-shandong-yantai-penglai-pavilion.jpg",
  "Shandong::Weifang Kite Culture": "/images/destinations/optimized/wiki-shandong-weifang-kite-culture.jpg",
  "Shandong::Yantai Penglai Pavilion": "/images/destinations/optimized/wiki-shandong-yantai-penglai-pavilion.jpg",
  "Shandong::Zibo Barbecue Streets": "/images/destinations/optimized/wiki-shandong-zibo-barbecue-streets.jpg",
  "Shanghai::Caoyang Community Market": "/images/experience-shanghai-wet-market.jpg",
  "Shanghai::Former French Concession": "/images/destinations/optimized/wiki-shanghai-former-french-concession.jpg",
  "Shanghai::Huangpu River Ferry": "/images/destinations/optimized/wiki-shanghai-huangpu-river-ferry.jpg",
  "Shanghai::M50 Art District": "/images/destinations/optimized/wiki-shanghai-m50-art-district.jpg",
  "Shanghai::Shanghai Breakfast Trail": "/images/experience-shanghai-wet-market.jpg",
  "Shanghai::Shanghai Museum": "/images/destinations/optimized/wiki-shanghai-shanghai-museum.jpg",
  "Shanghai::Shikumen Lanes": "/images/destinations/optimized/wiki-shanghai-shikumen-lanes.jpg",
  "Shanghai::The Bund": "/images/destinations/optimized/wiki-shanghai-the-bund.jpg",
  "Shanghai::Yu Garden and Old City": "/images/destinations/optimized/wiki-shanghai-yu-garden-and-old-city.jpg",
  "Shanxi::Datong Ancient City": "/images/destinations/optimized/wiki-shanxi-datong-ancient-city.jpg",
  "Shanxi::Fenyang Fenjiu Culture": "/images/destinations/optimized/wiki-shanxi-fenyang-fenjiu-culture.jpg",
  "Shanxi::Hanging Temple": "/images/destinations/optimized/wiki-shanxi-hanging-temple.jpg",
  "Shanxi::Hukou Waterfall Shanxi Side": "/images/destinations/optimized/wiki-shanxi-hukou-waterfall-shanxi-side.jpg",
  "Shanxi::Mianshan": "/images/destinations/optimized/wiki-shanxi-mianshan.jpg",
  "Shanxi::Pingyao Ancient City": "/images/destinations/optimized/wiki-shanxi-pingyao-ancient-city.jpg",
  "Shanxi::Qiao Family Courtyard": "/images/destinations/optimized/wiki-shanxi-qiao-family-courtyard.jpg",
  "Shanxi::Wutai Mountain": "/images/destinations/optimized/wiki-shanxi-wutai-mountain.jpg",
  "Shanxi::Yungang Grottoes": "/images/destinations/optimized/wiki-shanxi-yungang-grottoes.jpg",
  "Sichuan::Chengdu Market Cooking": "/images/destinations/optimized/wiki-sichuan-chengdu-market-cooking.jpg",
  "Sichuan::Chengdu Panda Base": "/images/destinations/optimized/wiki-sichuan-chengdu-panda-base.jpg",
  "Sichuan::Chengdu Teahouses": "/images/destinations/optimized/wiki-sichuan-chengdu-teahouses.jpg",
  "Sichuan::Danba Tibetan Villages": "/images/destinations/optimized/wiki-sichuan-danba-tibetan-villages.jpg",
  "Sichuan::Dujiangyan Irrigation System": "/images/destinations/optimized/wiki-sichuan-dujiangyan-irrigation-system.jpg",
  "Sichuan::Jiuzhaigou Valley": "/images/destinations/optimized/wiki-sichuan-jiuzhaigou-valley.jpg",
  "Sichuan::Leshan Giant Buddha": "/images/destinations/optimized/wiki-sichuan-leshan-giant-buddha.jpg",
  "Sichuan::Mount Emei": "/images/destinations/optimized/wiki-sichuan-mount-emei.jpg",
  "Sichuan::Ya'an Mengding Tea Mountain": "/images/destinations/optimized/wiki-sichuan-ya-an-mengding-tea-mountain.jpg",
  "Tianjin::Ancient Culture Street": "/images/destinations/optimized/wiki-tianjin-ancient-culture-street.jpg",
  "Tianjin::Dule Temple Jizhou": "/images/destinations/optimized/wiki-tianjin-dule-temple-jizhou.jpg",
  "Tianjin::Five Great Avenues": "/images/destinations/optimized/wiki-tianjin-five-great-avenues.jpg",
  "Tianjin::Haihe River Night Walk": "/images/destinations/optimized/wiki-tianjin-haihe-river-night-walk.jpg",
  "Tianjin::Italian Style Area": "/images/destinations/optimized/wiki-tianjin-italian-style-area.jpg",
  "Tianjin::Porcelain House": "/images/destinations/optimized/wiki-tianjin-porcelain-house.jpg",
  "Tianjin::Tianjin Eye Area": "/images/destinations/optimized/wiki-tianjin-tianjin-eye-area.jpg",
  "Tianjin::Tianjin Snack Trail": "/images/destinations/optimized/wiki-tianjin-tianjin-snack-trail.jpg",
  "Tianjin::Yangliuqing New Year Painting": "/images/destinations/optimized/wiki-tianjin-yangliuqing-new-year-painting.jpg",
  "Tibet::Basum Lake": "/images/destinations/optimized/wiki-tibet-basum-lake.jpg",
  "Tibet::Ganden Monastery": "/images/destinations/optimized/wiki-tibet-ganden-monastery.jpg",
  "Tibet::Jokhang Temple": "/images/destinations/optimized/wiki-tibet-jokhang-temple.jpg",
  "Tibet::Lhasa Barkhor": "/images/destinations/optimized/wiki-tibet-lhasa-barkhor.jpg",
  "Tibet::Namtso Lake": "/images/destinations/optimized/wiki-tibet-namtso-lake.jpg",
  "Tibet::Potala Palace": "/images/destinations/optimized/wiki-tibet-potala-palace.jpg",
  "Tibet::Tashilhunpo Monastery": "/images/destinations/optimized/wiki-tibet-tashilhunpo-monastery.jpg",
  "Tibet::Yamdrok Lake": "/images/destinations/optimized/wiki-tibet-yamdrok-lake.jpg",
  "Tibet::Yarlung Valley": "/images/destinations/optimized/wiki-tibet-yarlung-valley.jpg",
  "Xinjiang::Hotan Bazaar": "/images/destinations/optimized/wiki-xinjiang-hotan-bazaar.jpg",
  "Xinjiang::Kanas Lake": "/images/destinations/optimized/wiki-xinjiang-kanas-lake.jpg",
  "Xinjiang::Karakoram Highway": "/images/destinations/optimized/wiki-xinjiang-karakoram-highway.jpg",
  "Xinjiang::Kashgar Old City": "/images/destinations/optimized/wiki-xinjiang-kashgar-old-city.jpg",
  "Xinjiang::Kuqa Grand Canyon": "/images/destination-kuqa-grand-canyon-real.jpg",
  "Xinjiang::Nalati Grassland": "/images/destinations/optimized/wiki-xinjiang-nalati-grassland.jpg",
  "Xinjiang::Tianshan Tianchi": "/images/destinations/optimized/wiki-xinjiang-tianshan-tianchi.jpg",
  "Xinjiang::Turpan Grape Valley": "/images/destinations/optimized/wiki-xinjiang-turpan-grape-valley.jpg",
  "Xinjiang::Yining Kazanqi": "/images/destinations/optimized/wiki-xinjiang-yining-kazanqi.jpg",
  "Yunnan::Dali Old Town and Erhai": "/images/destinations/optimized/wiki-yunnan-dali-old-town-and-erhai.jpg",
  "Yunnan::Jingmai Mountain Tea Forest": "/images/destinations/optimized/wiki-yunnan-jingmai-mountain-tea-forest.jpg",
  "Yunnan::Kunming Zhuanxin Market": "/images/experience-kunming-zhuanxin-market.jpg",
  "Yunnan::Lijiang Old Town": "/images/destinations/optimized/wiki-yunnan-lijiang-old-town.jpg",
  "Yunnan::Shangri-La Dukezong": "/images/destinations/optimized/wiki-yunnan-shangri-la-dukezong.jpg",
  "Yunnan::Shaxi Ancient Town": "/images/destinations/optimized/wiki-yunnan-shaxi-ancient-town.jpg",
  "Yunnan::Stone Forest Kunming": "/images/destinations/optimized/wiki-yunnan-stone-forest-kunming.jpg",
  "Yunnan::Xishuangbanna Dai Villages": "/images/destinations/optimized/wiki-yunnan-xishuangbanna-dai-villages.jpg",
  "Yunnan::Yuanyang Rice Terraces": "/images/destinations/optimized/wiki-yunnan-yuanyang-rice-terraces.jpg",
  "Zhejiang::Longjing Village": "/images/destinations/optimized/wiki-zhejiang-longjing-village.jpg",
  "Zhejiang::Nanxun Ancient Town": "/images/destinations/optimized/wiki-zhejiang-nanxun-ancient-town.jpg",
  "Zhejiang::Ningbo Tianyi Pavilion": "/images/destinations/optimized/wiki-zhejiang-ningbo-tianyi-pavilion.jpg",
  "Zhejiang::Putuo Mountain": "/images/destinations/optimized/wiki-zhejiang-putuo-mountain.jpg",
  "Zhejiang::Shaoxing Old City": "/images/destinations/optimized/wiki-zhejiang-shaoxing-old-city.jpg",
  "Zhejiang::West Lake": "/images/destinations/optimized/wiki-zhejiang-west-lake.jpg",
  "Zhejiang::Wuzhen Water Town": "/images/destinations/optimized/wiki-zhejiang-wuzhen-water-town.jpg",
  "Zhejiang::Xitang Ancient Town": "/images/destinations/optimized/wiki-zhejiang-xitang-ancient-town.jpg",
  "Zhejiang::Zhoushan Fishing Coast": "/images/destinations/optimized/wiki-zhejiang-zhoushan-fishing-coast.jpg"
};
